const arts = {
  chaosHead:
  `
        ▄████▄   ██░ ██  ▄▄▄       ▒█████    ██████
        ▒██▀ ▀█  ▓██░ ██▒▒████▄    ▒██▒  ██▒▒██    ▒
        ▒▓█    ▄ ▒██▀▀██░▒██  ▀█▄  ▒██░  ██▒░ ▓██▄
        ▒▓▓▄ ▄██▒░▓█ ░██ ░██▄▄▄▄██ ▒██   ██░  ▒   ██▒
        ▒ ▓███▀ ░░▓█▒░██▓ ▓█   ▓██▒░ ████▓▒░▒██████▒▒
        ░ ░▒ ▒  ░ ▒ ░░▒░▒ ▒▒   ▓▒█░░ ▒░▒░▒░ ▒ ▒▓▒ ▒ ░
        ░  ▒    ▒ ░▒░ ░  ▒   ▒▒ ░  ░ ▒ ▒░ ░ ░▒  ░ ░
        ░         ░  ░░ ░  ░   ▒   ░ ░ ░ ▒  ░  ░  ░
        ░ ░       ░  ░  ░      ░  ░    ░ ░        ░
        ░
`
  ,
  chaos:
`   WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNNNNNWWWWWNNNNNWWWWWNNNNNWWWWWNNNNWWWWWNNNNNWWWWWNNNNNWWWWWNNNNNWWWWWNNNNNWWWWWNNNNNWWWWWNNNNWWWWWWNNNNWWWWWNNNNNNNXK0Okkkxxxxxxxdxkk0NWWWWNNNNNWWWWWNNNNNWWWWWNNNNNWWWWWNNNNWWWWWWNNNNWWWWWNNNNNWWWWWNNNNNWWWWWNNNNNWWWWWNNNNNWWWWWNNNNNWWWWWNNNNWWWWWNNNNNWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXX0xolcccc:::::::::::::::dOKNWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWNNNNNNNWWWNNNNNNNWWNNNNNNNWWWWNNNNNNWWWWNNNNNNWWWNNNNNNNWWWNNNNNNNWWWNNNNNNNWWWNNNNNNNWWWNNNNNNWWWWNNNNNNWWWNNNKd;;cccc::::::::::;;,,,,,,:xXNNNNNNWWWNNNNNNNWNWNNNNNNWWWNNNNNNNWWWWNNNNNNWWWNNNNNNNWWWNNNNNNNWWWNNNNNNNWWWNNNNNNNWWWNNNNNNWWWWNNNNNNNWWWNNNNNNNWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNXxc;;::::ccc::;,,,,,'.......,lxOXWNXKKKXNWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNNWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXKkl:;;:cccc:;,'.. ........      ..;ddlccllld0NNNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNNWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWNNNNNNNWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWNNNNNNNWWWWNNNNNNWWWNNNNNNWWWWNNNNNNNWWWNNNNNNNWWWNNNNNNNXkl::::cccc:,..    .........         ....,;;;,;lkKNWNNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWNNNNNNNWWWNNNNNNNWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXK0xl;;;:cllc:;'.    .............         ...',;;;,;cxOKKKXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWNWWNNNNNNNNNNNNNNNNNWWWNNNNNNNNNNNNNNNNNWNNNNNNNNWNWNNNNNNNNNWNNNNNNNNWNNNNNNNNNWNNNNNNNNWWNNNNNNNNNNNNXkoc:;,;;:cllc:,.   ...................     .';,'';;:::;;;:clodOKNNWNNNNNNNWNNNNNNNNNNWWNNNNNNNNWNNNNNNNNNWWNNNNNNNWNNNNNNNNNNNNNNNNNNNNWNNNNNNNNNNWNNNNNNWWNWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNXXXKkl;,,;;;:clllc;..   ......................   .,cc:,,,;:cc:,''',,;cdOXXNWWWWNXXXXNWWWWNXXXNNWWWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNNWWWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWXOOkl'.',,;:cllllc,.   ....''''..''''''''.......   .,ccc:;,,:cc:;,'',,,,oKXNWWWWNXXXXNWWWWNXXXNNWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWNNNNNNNWWWNNNNNNWWWWNNNNNNWWWWNNNXOc,'.....';::cc:;'......',,,,,,,,,,;;;::::::::;;,..  .,cllc;',::::;,',,;;dXWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWN0x:.   ....',;;::,...';;:::::::;;;;;;;;,;;;;;;;::ccc:,.. .':ccc;,;::c:;,,;:;ckXNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNOc'.   .....',;;;,..';;;;;,,,,,,'.',,''''.......'',,;:::;.   .;cc:;;;:cc:,,;:;;;oKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWWXOc.   .....'''',,,'...,;,,,'...........'''............'',;,'.  .';:c:,,;cc:,,;::;,:kWWWWNXXXXNWWWWNXXXXWWWWWNXXXXWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNNXXXNWWWWNXXXXNWWWWNXXXNNWWWWNXXXNNWWWWNXXXNWWWWWNXXXNWWWWKo'   .....'''',,,,'.. .''',''..........',,,''............'','.  .';ccc;,;cc:,';::;,;dXWWWNXXXNNWWWWNXXXNNWWWWNXXXNNWWWWNXXXNWWWWNNXXXNWWWWNNXXXNWWWWNXXXXNWWWWNXXXNNWWWWNXXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNNXNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNWWWWNNXNNNWWWWNNXOd;.......'',,,,,;;;,..  .......  ........',,,,,;,.. .......',,,.  .':ccl:;:cc:'';:::;;lOXXNNWWWWNNNNNNWWWWNNNNNNWWWWNXXXNNWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWNXXXNWWWWWNXXXNWWWWXx:'...',,',,,,,,;;:::,..    ......  .....','',,,,,;;,',,,;;;;;,,;,.  .,:ccc:;:c:;,',;:;;,;dKXXNWWWWNXXXXNWWWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXkc'.....','''',,,;:ccc:,.     .',,;;,',,,,,,',,,,,,,,,,,;;;:::::::;;'  .,clccc:::::;,,;;:;,,:xXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWNXXXNWWWWWNXXXNWWWWWXkc'.''.........',;:cccc:ll'     .';;::;;,,,,,,,,;;:;:::::;,,,;;:;;::;,'. .;clclc:::cc:;,,;;,,'':kNNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWNNXXXNWWWWNNXXNNWWWWNNXXNNWWWWNNXXNNWWWWNXXXNNWWWWNXXXNNWWWWNXXXNWWWWNx,..','',''.....';::::::o0Xl.    .',,,,,'',;;;::::cc:;;:ccc::;;;;;;;;,'.. .;clccc::::;;,',''''..'c0NXXXNNWWWWNXXXNNWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNNXXXNWWWWNNXXNNWWWWNNXXNNWWWWNNXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWNNXXNNWWWWNNXXNNWWWWNNXXNNWWWWNNXXNNWWWWNNNXNNWWWWNXXXNWWWWWNXXKd,...,,,,,,'.....';;::::lOXXk'     ....'',;::,.',;:;'..';cccccc::;,,,,''.. .,:cc:;;,,,,,,''.......;xNWWWWNNXXNNWWWWNXXXNNWWWWNXXNNNWWWWNXXXNWWWWNNXXXNWWWWNNXXNNWWWWNNXXNNWWWWNNXXNNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWNXXXNWWWWWNXKx'....',''',,'....,;::::l0NXX0c     ....';;:::;,'';;;,,;:ccclllcc::;;,''..   .;:::;;,'''',,'........;kNWWWNXXXXNWWWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXO:......''''''....,;;;;:o0NNNX0;      ..,;;:::cccccclllllllllllllccc:;,''..   .',;;;;;,''''''''.......,xXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWNXXXNWXo.  ..............,;;:okKKKXKO:.      .,:;;::cclooooooooooooooollcccc::,'..    .',,,,,,,,'....'........,xKXNWWWWNXXXXNWWWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNNXXNNWWWWNNXXNNWWWWNNXNNNWWWWNNXXNNWWWWNNXXNNWWWWNXXXNNO;. .....'...     ..ck0XXK0Oko'        '::;;:ccllooooooooooooooolllcccc:;'..     .',''',,,''.............cOKNWWWWNNXXNNWWWWNXXXNNWWWWNXXXNWWWWNNXXNNWWWWNNXNNNWWWWNNNXNNWWWWNNXXNNWWWWNNXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWNNXXXNWWWWNNXXXNWWWWNNXXXNWWWWNXXXNNWWWWNXXXNWWWWWNXXXNWWWWN0c.  ........       'dKXXKOd:'.        .,c:;:::cccllllllllloooolllcc:::::,..       .','''''''''...........'cd0XXXNNWWWWNXXXNNWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNNXXXNWWWWNXXXNNWWWWNXXXNNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWNXXXNWWWWNx'   ........       ;OKXKk:.            .;:;,;;:::cccc:::::::::clc,.';:::,.         .,''.'''''''....'''.....'o0XXXNWWWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKo.   .......        ;OKkl'               .,,...,,',,;;,;;;:cc:cdxc'.;:::;..          .''.....'''''..''..'.....,cxKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWNXXXNWWWWWNXXXk;.   ......         .',.                 .,;,..';;:cloodxxxkkxxxo:::ccc;'.           .''.....'''''''''''''... ...;oOKXXWWWWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWNNNNXx,    ......                              .;:::,,:ccclllooooddoolcccccc:'.            .'''....'''''',,,,''''...    .,lkKNWWWWNNNNNNWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNNWWWWNXXXNWWWNd.    .....                               ':c::::ccccclllllllllcclllll:,.            .'''.......''',,,,,,,,,'...   ..:dKXXXXNWWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWNXXXNWWWXo.    .....                               .,:c::;;::cccccccccccccllllc,..           ..;;'...  ....',,,;;;,,''''..   ..:OXXXXNWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWNNNNNNNNNNNNNNO;     ....                                 .:lc::;;;;;;;:::ccccccllll;..          ..';::,'..  ..',,;;;;;,,,,,''...   ..c0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWNXKd'     ....                                 .,:::::;;;;;:::cccccccllc:'.         ...,;:::;'.......,,;;,,,,;;;;'....    ..oNWWWNXXXXWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNNNNNNWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWNNN0c.    .....                                  .',:::;;,,;;::cccclccc;'..       ....,;;:::::,........',,,;,,''''''.'..    .;ONWWNNNNNNWWWWNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWNXXXNWNx'     .....                                    .',;::;,,,;:ccccc;;,.         ...',;;:;;::;,..  .....''''''..'''....      .dKXNNWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWNXXXNNKl.     ..''.        ..                            ..',;'',;;:c:;,.'..        ...'',;;;;;;;,'..     ..'''.'..........      .c0XXNWWWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNNNNNNWNWNNNNNNNWWWNNNNNNNNNNNNNNNNWWWWNNNNNNWWNWNNNNNNWNWNNNNNNNNNNNN0c.     ..''.        ..                               ....',,,'........      ....'',,,,,,;,'..      ...',,'..........      .;kXNNNNNNNNNWNNNNNNNNNNNNNNNNNWNNNNNNNNWWWNNNNNNNWNNWNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWW0l..   ......         ..                                   . ..    ......    .....''''',,,,''..      ...''''.........       .'xNWNXXXXWWWWWNXXXNWWWWWXXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNNNNNNWWWNNNNNNNWWWNNNNNNNWWNNNNNNNNWWWNNNNNNWWWWNNNNNNWWWNNNNNNNWWNXo'..  .......       .....                                           .....     ........'''''...       ........... ..          'xXNNNNNNNWWWNNNNNNNWWWNNNNNNNWWWNNNNNNWWWWNNNNNNWWWNNNNNNNNWWNNNNNNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWWXXXXNWWWWNNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWNXXXOo,.     .....      ......                                           .....     ........'.......       ...........            .'xKXWWWWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWNNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWNXXKOd;.     .....    ........                                           ......     .............          .........             .'oKNWWWWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNNNNNNWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWNNNNNNNWWWNNNNNNNWWWNNNNNNNWWNOc....   ......   .........                                               .     .............           ........     ..      ..oXNNNNNNNWWWNNNNNNNWWWNNNNNNWWWWNNNNNNNWWWNNNNNNNWWNNNNNNNWWWNNNNNNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWXOl'.... ....''.............                                 ...                 .............           .......      ...     .:xXWNXXXXWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNNNNNNWWWNNNNNNNWWWNNNNNNNNNNNNNNNNNNWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKd.........................                         ..      ......                    .......           .......       ..     .lOXNNNNNNNWWWNNNNNNNNNWNNNNNNNNNNNNNNNNNNNNNNNNNNWWNNNNNNNNNNWNNNNNNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWNXXXXWWWWWNXXXx,..  .....................                         ..      ........                                     .......            ..o0XXWWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWNNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWNXXOc...  ......................                                .........                                    .......            .'xXXNWWWWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNNNNNNWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNXNNNWWWWNNNNNNWWWWNNNNNNNKd,..  .....  ................                               ..........     ..                             .......       .    .,kNWWNNNNNNWWWNNNNNNNWWWNNNNNNWWWWNNNNNNWWWWNNNXNNWWWWNNNNNNWWWWNNNNNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNNKo'..     .    .................    .                         ..........     ..                             .......   ..       .:KWWWNXXXXWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKkc....  ..      .................                              ...........  ....                             ........   .      ..:0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWXkc,..    ..       ................                             ............  ........                          .......          ..;OXXNWWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNXXXXNWWWWNXXXNNWWWWNXXXNNNNXOo;.     .        .................        ..                   ...........  ........                          .........          .l0XNWWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNNXXXNWWWWNXXXXNWWWWNXXXNNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXNNNWWWNNNXNNNWWWNNNNNNWWWWNNNXNNWWWWNNNXNNWWWWNNNNNNWWWWNXX0Ox:..            .  ................      ..                    ............ .........                 ..      .........           .c0NNNXNNNWWWNNNXNNWWWWNNNNNNWWWWNNNNNNWWWWNNXNNNWWWWNNXXNNWWWWNNNNNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWNXKK0xc,.               ................      .                     ......................                 ...     ........             .;OXXXXXWWWWWNXXXNWWWWWXXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKko;.                ................                            ......................                  ..    .........       .     .,l0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWNKOo:,.              .. ...............                            .....................                  ............... ...  ....   .;d0WWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWNNXXXNWWWWNNXXXNWWWWNXXXNNWWWWNXXXNNWWWWNXXXNNWWNKOk:.                  ..............                            .....................                   .............. .............'dXWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNNXXXNWWWWNNXXNNWWWWNNXXNNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWNNXNXNWWWWNNXXXNWWWWNNNNNNWWWWNNNXNNWWWWNXNXNNWWWWNXNXXXd'..                ...............                            .....................                    .. .     ............... ...:kXNNNWWWWWNNNNNWWWWNNXNXNWWWWNNXNXNWWWWNNXNNNWWWWNNNNNNWWWWNXXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXKxc'.                ...............                              ........ ..........                             ...............   ..:OXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNK0d,.                  .............                             ......... ........                               ............        ,ONNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWXKd'.              .    ............                              ......    ....                                   ..........         'xXWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNNNXNWWWWNNNNNNWWWWNNXXNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWNNXx,..                   ...........                               ....       .                                    ..........         .;kNWNXXNNNWWWNNXXNNWWWWNNNNNNWWWWNNNNNNWWWWNNXNNNWWWWNNXXNNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNNXXNNWWWWNXXXXNWWWWNXXXNNWWWWNXXXNWN0l'.             .     ..........                               .....                                             .........          .:OXWWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNNXXXNWWWWNNXXNNWWWWNXXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWKx;..           .       .........                              ......                                              ........         .'lkKNWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXO:.                     .......                               ......                                              ........    .    .:kXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWWXXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWNXXKo...                    ......                              .......                                              ....  ..    .    'lkXWNXXXNWWWWWXXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNKxc:;.                  ......                             .........                                              . ..  .    ...  .'d0KNNNNNNNWWWNNNNXNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNXNNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNNWWWWNXXXNNWWN0xdd:.   ....         ......                                 ..  .                                                     .    ..   .;ok0XWWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNXXXXNWWWWNXXXNNWWWWNXXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWKkkOo'. .........   ......                                                                                            ..  ........cOO0XWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWNNNNNNNNNWNNNNNNNNNNNNNNNNNNNNNNNNNXKXK0d;,;:;''..............                                                                                           ........ .:ooONNXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWNXXXXNWXX0ddkOxl;............;,.                                                                                         ........  .cKK0XWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWNNNNNNNWWWNNNNNNNWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWNNNNNNNWNNKOKXKOl;'...:c,,,':dx:..                                                                                        ...... .  .cKNXXNWNNNNNNWWWNNNNNNNWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWNXXXXNWWKo;';ccxX0dxdd0KOo;.                                                                                        ...       .dNNXXXNWWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWNXXXNWWXOkkO0KKNWK0K00KKKKk'                                                                                       ....      .,ONNXXXNNWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWNWWNNNNNNNWNNNNNNNNNNNNNNNNNNWWWNNNNNNNNWNNNNNNNNNWWNNNNNNNNNWNNNNNNNWWNNNXXXNNNWNNNNKXNNWNNNXd. .                                                                                     .....   ...cKNNNNWNNNNNNNWWWNNNNNNNWNNNNNNNNNWNNNNNNNNNNWNNNNNNNWWWNNNNNNNNWNWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNKo;c;.                                                                                    . ..  .....dXXWWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWNNNNNNNWWWNNNNNNNWWWNNNNNNNWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWNNNNNNNWWWNNNNNNNWWWNNNNNNNWWWNXKKKl. ..                                                                                      ... .;ONNNWWWNNNNNNNWWWNNNNNNNWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWNx'':,.                                                                        .           ... ..dNWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWW0dxOo..                                                                      ...          .....cKWWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWNNNNNNNWWWNNNNNNNWWWNNNNNNWWWWNNNNNNWWWNNNNNNNWWWWNNNNNNWWWNNNNNNNWWWNNNNNNNWWWNNNNNNWWWWNNNNNXKXNKo,.                                                                                  ...',oXNNNNWWWNNNNNNNWWWNNNNNNNWWWNNNNNNWWWWNNNNNNNWWWNNNNNNWWWWNNNNNNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNNWWWXx;                                                             ..                  ..''lxOXXXXWWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWNNNNNNNNNNWNWNNNNNNNWWNNNNNNNNNWWNNNNNNNNWNNNNNNNNNWNNNNNNNWWWNNNNNNNNNNNNNNNNNWWNNNNNNNNNWNNNNNNNNNNNNKl,..                                                          ..                  .;odOXNNNNNNNNWNNNNNNNNNWNNNNNNNNNWNNNNNNNWNNNNNNNNNWNNNNNNNNWWNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNNKOd'                                                                              .;x0KXNWWWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNNWWWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNXXXXNNNXd.                                                                 ...............,d0XNWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWNNNNNNNWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWNNNNNNNWWWNNNNNNNWWWNNNNNNWWWWNNNNNNWWWWNNXk:..                                                          ..............''''.....:OXNNNNNWWWWNNNNNNWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWNXKKKKXXK0Okdl::.                                                        ...............'''',,,''..,d0XXXWWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0xolooooooc;,''',,'.............                                                  ...''''''.........'''',,,...'xXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWNXXXNWWWWN0d:,'.........       ..................                                              ..................'',..'','. .:0WWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNNXXXNWWWWNXXXXNWWWWNXXXNNWWWWNXXXNNWWWWNXXXNNXOo:'....'''.''.............................                                             .................'..''..''... .dNWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNNXXXNWWWWNXXXXNWWWWNXXXNNWWWWNXXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNXNNWWWWNXNNNNWWXOl,........''........... ................'''..... .                                         ....   .........'...'''.......lKNNWWWWNNNNNNWWWNNNNXNWWWWWNNNNNWWWWNNNXNNWWWWNNNNNNWWWWNNXXNNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWNXXXNWWW0:................'''......  .......'''''''...............                                   ..      .............''.... ..oKXWWWWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXx'.........   ....'''''.....   .....''''''.....','...........                              .....    .............''.......,ONNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWNX0c..........   ......''''......     ....'''....'',,,''''.........                          .......  .................... ..oNWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWNNXXXNWWWWNNXXXNWWWWNNXXNNWWWWNXXXNNWWWWNXXXNNWWWWNXXXNNWWWWNXKl..........  ......................  ....'''.'',,;,,''',,''.........                    ..............................  ..xWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNNXXXNWWWWNNXXXNWWWWNNXXNNWWWWNXXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWNNXXXNWWWWNNXXNNWWWWNNXXNNWWWWNXXNNNWWWWNXXNNNWWWWNXXXNWWWO;......... ...............................''',,,;;;,,''',,''''''''......              ..............    ............. ..:OXXNNWWWWNXXXNWWWWWNXXXNWWWWNNNXXNWWWWNNNXXNWWWWNNXXNNWWWWNNXXNNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWNXXXNWWWNd'.............................. ...........',,,;;;;;,,,,''''..''''....'...          .............      ...........   .'dKXXXWWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXk:.. ..................  ...................',,;;::;;;;,,,''.............          . ...........       ..........   .'dKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWNXXXNNKl.   ..............  ........................',,;;;;;;,,,'.........            ........... ...      ..........    .cKNWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNNWWWWNXXNNWWWWNNNNXNWWWWNNXXNNWWWWNXNXNNWWWWNNNXNNWWWWNXNNNNWWWWNXXXNWWKl.     ........... .................... ........'''',,,,''....              .................      .....        .;kXNWWWWNXXNNNWWWWNNXNNWWWWNNNNXNWWWWNNXNNNWWWWNNXNXNWWWWNNNXNNWWWWNXXNNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNNXXXNWWWWNXXXNNWWWWNXXXNNWWWWNXXXNWWWWWNXXKx;...     ............ .................... ..............    .....      ....................    .....        .'dXNNXXXNNWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNNXXXNWWWWNXXXNNWWWWNXXXNNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWNXXXNWWWWWNXXXXXOxc..       ........  .................................   .....    ..............'.........   .....         .;OWWNXXXXWWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0ko,.            ...............................     .......   ..........................   ....          .oKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWNXXXNWWWWWXXXXXNO:..           ............................      ......   .........................   ......           'kXXXNWWWWNXXXXWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNNNXNNWWWNNNXNNWWWWNNNXNNWWWWNNNXNNWWWWNNNNNNWWWWNNNNNNWWWWNNXNNNWWWNNNXNNNWWWNNXXNNWNOl,.           ..  ......................    .....     .......................        ....       .....,kNXNNWWWWNNNNNNWWWNNNXNNNWWWNNXXNNWWWWNNNNNNWWWWNNNNNNWWWWNNXNNNWWWWNNXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWNNXXXNWWWWNNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWNNXKxd:.           ..   ............. ....    ....       ..................   .    .    ....     ....coc;c0WWWNXXXNNWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWNXXXNWWWWWNXXXNWWWWWXXXK0o.              ..   .....  ...                  ...............            .    ...      ....lO0OO0XWWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXo.                                            ................                   ..    .,'..'o0NNXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNd'                                 .............................        ..........';c::d0OllxKNWWWWNXXXXNWWWWNXXXXWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNNNNNNWWWNNNNNNNWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWNNNNNNNWWWNNNNNNWWWWNKd'                            ...'',''........',,,'''...... .        ..',,,''''',:ooooollldOXNWWWWNNNNNNWWWNNNNNNNWWWNNNNNNNWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWXkc'..                       ..''''......''',,;;,,''....            ..',;;;;;;;,,;;;;;'.,:;cxXXXXNNWWWWNXXXNNWWWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWXOxocc:'..              ...',''''..'',,''''',,'....             ...,;;;;,,,,,''',,,..',,;o0XXXXNWWWWNXXXNNWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNNNNNNWWNNNNNNNNWNNNNNNNNNNNNNNNNNNWWWNNNNNNNNNWNNNNNNNNWWNNNNNNNNNWNNNNNNNWNWNNNNNNNWNNNNNNNNNWNNNXKOkdl,.         .',;;;,,,''''........''....              ...',,'''........'''''',:xXNWWNNNNNNNNWNNNNNNNNNNWNNNNNNNWNNNNNNNNNWWNNNNNNNNWNNNNNNNNNWWNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWNXXXXWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWXOo:'.   .';;;;;;;;,,,''.............              ....''''''...........',cdOXNWWWWNXXXXNWWWWNXXXXWWWWWNXXXNWWWWWXXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNNNNNNWWWNNNNNNNWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWNNNNNNNWWWNNNNNNNWWWNNNNNNNWWWNNNNNNNWWWNNNNNNNWWWNNNNNNNWWWNKOl'.';::::;;::::;,,'......                    ...'''''''.......',:dk0KXNNNWWWNNNNNNNWWWNNNNNNNWWWNNNNNNNWWWNNNNNNNWWWNNNNNNNWWWNNNNNNWWWWNNNNNNWWWNNNNNNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWNNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWXo;;;::;;;;:::c:::;;,,''...                  ..'''''''......';:coOXNWWWWNXXXXNWWWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWKd:;;;;;;;;:::::cc::::::;;,'..                ..'''''.......',;:clOXNWWWWNXXXXNWWWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNNNNNNWWWNNNNNNNWWWNNNNNNNWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWNNNNNNNWWWNNNNNNNWWWNNNNNNNWWWNNNNNNNWWWNNNNNNWWWWN0o;;,,,;;;::::::cc::c:c:c:::;;,'.              ..'''''''',,,,,,,;:coO0O0XNNWWWNNNNNNNWWWNNNNNNNWWWNNNNNNNWWWNNNNNNNWWWNNNNNNWWWWNNNNNNWWWWNNNNNNNWWWNNNNNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWNXXXNWWWWWXXXXNWWWWWXXXXNWWWWNXXXXNWWWWXd;;;,,,;;:::cc:;::;;::cc:::::::;,.             ...'',,,;;;;;,,''',,;::;:o0NWWWWNXXXXNWWWWNXXXXWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNNNNNNWNNNNNNNNNWWWNNNNNNNWWNNNNNNNNWWWNNNNNNNWWNNNNNNNWNWNNNNNNNNNNNNNNNNNWNWNNNNNNNWWNNNNNNNNWWNNNNNNNNNWWKo,',,;;:::cccc:;,,,;;:::;::::cc:;;,..           ...'''',;;;;,,,,,'',,;,,;xXNXXNNNNNNNWWNNNNNNNNWNWNNNNNNNWNNNNNNNNNWWNNNNNNNNNNNNNNNNNWWWNNNNNNNWNNNNNNNNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNk:,,;;:ccccc::;,',;;;,,,;::::ccccc::;,....       ....''',;;,,,;;,,',,,,,cxdlccdKWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNNWWWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNNXXXNWWWWNXXXXNNk:,,;;:ccc:;;;,,;;,,,;;;,;;:c::::::::::;;;,',;;.  ...''',,''',,,,,,,'..,,,,,,;lkKNWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWNNNNNNNWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNXd;;;;;:cc:;,,;;;,,,,;;,'',,,,;;;;',;:;;;::::cdkxo,...'',,;,,,,,,,'.....',,,,,,'';o0NNNNNNNNNNNWWWNNNNNNWWWWNNNNNNNWNWNNNNNNNNNNNNNNNNWWNNNNXNNNNWWWNNNNNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWNXXXNWWWWWXXXXNWWWWWXXXXNWWWWNXXXXNWWWWNKo;;;;;;::;'...'',,,,,''.''''''''...';;,;;:::;,;cdxl'...',;;;;,,'....',,,;;;,'..',ckXWWWNXXXXXWWWWWNXXXNWWWWNNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKdc;;;:oxkxoc,.........''............',;:::::;,;:dKKOdc;'..''''''',,,;,,,'''',,,;:kXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWX0OO0KNWWWN0xl;'....................',;;,;;,,;;c0WWNXKOxoooolc;;,,,,,''',;;;;;:d0XXXXXNWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWNNXXXNWWWWNNXXXNWWWWNNXXXNWWWWNXXXNNWWWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWWNXXXNWWWWNNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXKOxdc:;.................''''',;;;cOWWNNXXXNNWWNKOkdlc;;:ldkkkkO0XNNXXXXXNWWWWNXXXNWWWWNNXXXNWWWWNNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNXNNNWWWWNNNNNNWWWWNNNNNNWWWNNNNNNWWWWNNNNNNWWWWNNNNNNWWWWNNNXNNWWWWNNNNNNWWWWNNXXKOxo:,.......... ...'',;:::lOXNNWWWWNNXNNNWWWNX000XNNWWWNNNNNNWWWNNNNNNNWWWNNNNNNNWWWNNNXXNNWWWNNNNNNWWWWNNNXNNWWWWNNXNNNWWWWNNNNNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWNKko:,'';cc;...,,,;:::lOXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWNXXXXWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKKXNNXOko;'',::cdXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWNXXXNWWWWWNXXXNWWWWWXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXNWWWWWWNXXXNWWWWWNXXXNWWXo'',:cdKWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXWWWWWNXXXNWWWWWNXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWNXXXXNWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWNNNNNWWWWWNNNNNWWWWWNNNNNWWWWNNNNNNWWWWNNNNNWWWWWNNNNNWWWWWNNNNNWWWWWNNNNNWWWWWNNNNNWWWWWNNNNNWWWWWNXNNNWWWWNNXNNWWWWWNNNNNWWWWWWNNNNNWWWWWNNNNNWWWXxoldOXWWWWWNNXNNWWWWNNNXNWWWWWNNNNNWWWWWNNNNNWWWWWNNNNNWWWWWNNNNNWWWWWNNNNNWWWWWNNNNNWWWWNNNNNNWWWWNNNNNWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
  `
  ,
  doomHead:
  `

          ██████╗  ██████╗  ██████╗ ███╗   ███╗
          ██╔══██╗██╔═══██╗██╔═══██╗████╗ ████║
          ██║  ██║██║   ██║██║   ██║██╔████╔██║
          ██║  ██║██║   ██║██║   ██║██║╚██╔╝██║
          ██████╔╝╚██████╔╝╚██████╔╝██║ ╚═╝ ██║
          ╚═════╝  ╚═════╝  ╚═════╝ ╚═╝     ╚═╝
  `
  ,
  doom:

`            XMX                   .HMM>
            MMMM.                dMMMM>
           'MMMMMX     .....   dMMMMMMX
           XMMMMMMMnMMMMMMMMMMMMMMMMMMM
          :MMMMMMMMMMMMMMMMMMMMMMMMMMMM>
          XMMMMM!"    "MMMMMM"\`  \`"MMMMM
          MMMM#         4MMf        \`MMMX
          XMMM            MX          'MMM:
         'MMM~            '>            MMM
         MMMf       .     '>            \`MMX
        MMMM>     :MMM    '>   :MMM      MMMX
       XMMMM      MMMM>   '>   XMMMX     MMMMk
      MMMMMM>     MMMM~   'k   MMMMX     MMMMMh
     MMMMMMMX     XMMM    XX   ?MMM     XMMMMMMM
     MMMMMMMMk     ^\`    X 'h    \`     :MM##MMM~
     ?MM>  ^?M.       .!    %.      .HM"   MM
    .?M      '"%+++!".nMMMMn "%++!*" %.. 'M..
      \`?M>+%L         <MMMMMMMM>       :   XM"
        'X   %        XMMMMMMMM>      X   'f
          X   \`M.      ?MMMMMM~    .HM   :\`
           %.  \`MMMx.          .xHMMM   X
           \`X  \`MMMMMMMMMMMMMMMMMMM  :f
            h:.M. 4MM     "     MM" xMM
            MMMMMM: \`%x.......x"\`.HMMMM
            MMMMMMMMMMhx.......xHMMMMMMM
`
  ,
  hankhead:
    `        ▄█    █▄       ▄████████ ███▄▄▄▄      ▄█   ▄█▄
       ███    ███     ███    ███ ███▀▀▀██▄   ███ ▄███▀
       ███    ███     ███    ███ ███   ███   ███▐██▀
      ▄███▄▄▄▄███▄▄   ███    ███ ███   ███  ▄█████▀
      ▀▀███▀▀▀▀███▀  ▀███████████ ███   ███ ▀▀█████▄
       ███    ███     ███    ███ ███   ███   ███▐██▄
       ███    ███     ███    ███ ███   ███   ███ ▀███▄
       ███    █▀      ███    █▀   ▀█   █▀    ███   ▀█▀
                                             ▀
      `
  ,
  hank:
  `
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXK0OOO000K00KK0000000OOOO0KXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKKKKXXXKKKK0OOOO0000KKKKKXXXKK0KWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0d0NNNXXKK0kl:;;;cok0KXKKKXXNNNOdKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;.,:lxk0KK0ko:;;;,,;o0K0Okdl;'.cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO'       .........    ...       ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx.                                ,kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl.                                  .dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.                                    'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo...''....                     ...''...xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo   ..',,,,;;;;;;;;;;;;;;;;;,,,,,'..  .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo              ..........             .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo            .;;;,''',,'.             .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo            ,0WXl.',oXNk'            .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo            '0MNd;:cxXXx'            .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo            '0MXl....dNWk.           .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo            'dkxc,,;:odo,            .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo                                     .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo             ':::,,'',;,             .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo             cXM0:...,:;.            .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo             ;XMKc,,,c,              .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo             :XM0,   ....            .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo             ;dxd:,'',:l'            .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo                                     .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo             ,cc:;,,,,:,             .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo             cNM0:...,:,.            .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo             ;XMKc,,;c,              .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo             :XM0,   ..'.            .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo             ;ddo:,',,:l'            .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo                                     .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo            .clc:,,;:c:,.            .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo            ,0MNl...:0MX:            .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo            '0MNo,lxON0c.            .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo            '0MNc.':xNNx'            .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.           'ldo,   .loo:.           .OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx'.....                        .....,kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOlccc;,'....................',:ccco0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKK0OxdoooooollcccclllloooodkO0KKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXK0OOOOOOOOOOOOOOOOOOOO0KXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM

  `
};

export default arts;
